spring:
  freemarker:
    checkTemplateLocation: false
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100